name: Daily AI Blog Post

on:
  schedule:
    - cron: "0 1 * * *" # 1 AM UTC daily
  workflow_dispatch: # lets you run manually from GitHub Actions tab

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate new post
        run: npx tsx generate-post.ts
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # Add your Supabase environment variables here
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # Remove the commit and push step as it's no longer needed
      # - name: Commit and push
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: 🤖 New AI blog post
      #     # Update file_pattern to include both posts and images
      #     file_pattern: posts/*.md public/images/*.png
